import type { Product, Order, Notification, SensorData, Review } from "./types";

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Smart Green Complete Kit",
    description: "Full hydroponic system with sensors, LED grow lights, and automated nutrient delivery. Professional installation in Erbil included.",
    price: 1299,
    image_url: "",
    emoji: "🌿",
    category: "kit",
    is_new: false,
    is_featured: true,
    stock: 15,
    care_instructions: "Setup requires 30 minutes. WiFi connection needed for sensor data. Refill nutrient reservoir weekly.",
    created_at: "2026-01-15",
  },
  {
    id: "prod-2",
    name: "Basil Royale",
    description: "Premium Italian basil cultivar optimized for hydroponic growth. Rich aroma and flavor.",
    price: 12,
    image_url: "",
    emoji: "🌿",
    category: "plant",
    is_new: false,
    is_featured: true,
    stock: 45,
    care_instructions: "pH 5.5-6.5, EC 1.0-1.6, Temperature 20-25°C. Harvest outer leaves first.",
    created_at: "2026-02-01",
  },
  {
    id: "prod-3",
    name: "Mint Luxe",
    description: "Spearmint variety with exceptional growth rate. Perfect for teas and garnishing.",
    price: 10,
    image_url: "",
    emoji: "🌱",
    category: "plant",
    is_new: true,
    is_featured: true,
    stock: 38,
    care_instructions: "pH 6.0-7.0, EC 1.2-1.6, Temperature 18-24°C. Pinch growing tips to encourage bushiness.",
    created_at: "2026-03-10",
  },
  {
    id: "prod-4",
    name: "Cherry Tomato",
    description: "Sweet cherry tomato variety bred for indoor hydroponic systems. Compact vine growth.",
    price: 18,
    image_url: "",
    emoji: "🍅",
    category: "plant",
    is_new: false,
    is_featured: true,
    stock: 22,
    care_instructions: "pH 5.5-6.5, EC 2.0-3.5, Temperature 20-28°C. Support vines as they grow. Pollinate flowers manually.",
    created_at: "2026-02-15",
  },
  {
    id: "prod-5",
    name: "Orchid Blanc",
    description: "Elegant white Phalaenopsis orchid adapted for semi-hydroponic culture.",
    price: 35,
    image_url: "",
    emoji: "🌸",
    category: "plant",
    is_new: true,
    is_featured: true,
    stock: 12,
    care_instructions: "pH 5.5-6.5, EC 0.5-1.0, Temperature 18-28°C. Provide 12h indirect light. Mist aerial roots.",
    created_at: "2026-04-01",
  },
  {
    id: "prod-6",
    name: "Lavender Dusk",
    description: "French lavender variety with intense fragrance. Compact growth ideal for indoor gardens.",
    price: 22,
    image_url: "",
    emoji: "💜",
    category: "plant",
    is_new: false,
    is_featured: false,
    stock: 30,
    care_instructions: "pH 6.0-8.0, EC 1.0-1.4, Temperature 15-25°C. Needs good airflow. Prune after flowering.",
    created_at: "2026-01-20",
  },
  {
    id: "prod-7",
    name: "Sage Imperial",
    description: "Culinary sage with silvery-green leaves. Rich, earthy flavor for Mediterranean dishes.",
    price: 14,
    image_url: "",
    emoji: "🌾",
    category: "plant",
    is_new: true,
    is_featured: false,
    stock: 28,
    care_instructions: "pH 6.0-7.0, EC 1.0-1.6, Temperature 15-24°C. Harvest before flowering for best flavor.",
    created_at: "2026-03-25",
  },
  {
    id: "prod-8",
    name: "Nitrogen Booster Pro",
    description: "High-concentration nitrogen supplement. 1L bottle for 40+ feeds.",
    price: 28,
    image_url: "",
    emoji: "💧",
    category: "nutrient",
    is_new: false,
    is_featured: true,
    stock: 60,
    care_instructions: "Add 5ml per 10L of water. Shake well before use. Store in cool, dark place.",
    created_at: "2026-01-10",
  },
  {
    id: "prod-9",
    name: "pH Down Solution",
    description: "Erbil-calibrated pH adjustment solution. 500ml bottle.",
    price: 22,
    image_url: "",
    emoji: "🧪",
    category: "nutrient",
    is_new: false,
    is_featured: false,
    stock: 55,
    care_instructions: "Add 1ml per 10L. Wait 30 minutes before re-testing. Use protective gloves.",
    created_at: "2026-01-10",
  },
  {
    id: "prod-10",
    name: "Bloom Stimulator",
    description: "Flowering support formula. Enhances bloom size and color intensity.",
    price: 35,
    image_url: "",
    emoji: "🌺",
    category: "nutrient",
    is_new: false,
    is_featured: true,
    stock: 40,
    care_instructions: "Apply during flowering phase only. 3ml per 10L every other feeding.",
    created_at: "2026-02-05",
  },
  {
    id: "prod-11",
    name: "LED Grow Light Panel",
    description: "Full-spectrum 150W LED panel optimized for indoor hydroponic gardens.",
    price: 89,
    image_url: "",
    emoji: "💡",
    category: "accessory",
    is_new: true,
    is_featured: true,
    stock: 20,
    care_instructions: "Mount 30-45cm above canopy. 16/8 light cycle for vegetative, 12/12 for flowering.",
    created_at: "2026-04-10",
  },
  {
    id: "prod-12",
    name: "Smart pH Meter",
    description: "Bluetooth-connected pH meter with auto-calibration and app integration.",
    price: 45,
    image_url: "",
    emoji: "📊",
    category: "accessory",
    is_new: true,
    is_featured: false,
    stock: 25,
    care_instructions: "Calibrate monthly with included solutions. Rinse electrode after each use. Replace electrode yearly.",
    created_at: "2026-04-15",
  },
];

export const mockSensorHistory: { day: string; ph: number; ec: number; temp: number; reservoir: number }[] = [
  { day: "Mon", ph: 5.9, ec: 1.6, temp: 21, reservoir: 82 },
  { day: "Tue", ph: 6.1, ec: 1.7, temp: 22, reservoir: 80 },
  { day: "Wed", ph: 6.0, ec: 1.7, temp: 21, reservoir: 78 },
  { day: "Thu", ph: 6.2, ec: 1.8, temp: 22, reservoir: 76 },
  { day: "Fri", ph: 6.3, ec: 1.8, temp: 23, reservoir: 79 },
  { day: "Sat", ph: 6.2, ec: 1.9, temp: 22, reservoir: 78 },
  { day: "Sun", ph: 6.2, ec: 1.8, temp: 22, reservoir: 78 },
];

export const mockCurrentSensors: SensorData = {
  id: "sensor-1",
  ph: 6.2,
  ec: 1.8,
  water_temp: 22,
  reservoir_level: 78,
  timestamp: new Date().toISOString(),
};

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    user_id: "user-1",
    items: [
      { id: "oi-1", order_id: "ord-001", product_id: "prod-1", product_name: "Smart Green Complete Kit", quantity: 1, price: 1299 },
    ],
    total: 1299,
    status: "delivered",
    payment_status: "paid",
    address: { id: "addr-1", user_id: "user-1", label: "Home", street: "100m Street, Dream City", city: "Erbil", country: "Iraq", phone: "+964 750 123 4567", is_default: true },
    created_at: "2026-01-20T10:30:00Z",
  },
  {
    id: "ord-002",
    user_id: "user-1",
    items: [
      { id: "oi-2", order_id: "ord-002", product_id: "prod-3", product_name: "Mint Luxe", quantity: 2, price: 10 },
      { id: "oi-3", order_id: "ord-002", product_id: "prod-8", product_name: "Nitrogen Booster Pro", quantity: 1, price: 28 },
    ],
    total: 48,
    status: "processing",
    payment_status: "paid",
    address: { id: "addr-1", user_id: "user-1", label: "Home", street: "100m Street, Dream City", city: "Erbil", country: "Iraq", phone: "+964 750 123 4567", is_default: true },
    created_at: "2026-04-25T14:15:00Z",
  },
  {
    id: "ord-003",
    user_id: "user-2",
    items: [
      { id: "oi-4", order_id: "ord-003", product_id: "prod-5", product_name: "Orchid Blanc", quantity: 1, price: 35 },
    ],
    total: 35,
    status: "shipped",
    payment_status: "paid",
    address: { id: "addr-2", user_id: "user-2", label: "Office", street: "Gulan Street", city: "Erbil", country: "Iraq", phone: "+964 750 987 6543", is_default: true },
    created_at: "2026-04-27T09:00:00Z",
  },
];

export const mockReviews: Record<string, Review[]> = {
  "prod-1": [
    { id: "rev-1", product_id: "prod-1", user_id: "user-2", user_name: "Sara Ahmed", rating: 5, comment: "Absolutely stunning system. Installation was seamless and the sensor data is incredibly accurate.", helpful_count: 12, created_at: "2026-02-10" },
    { id: "rev-2", product_id: "prod-1", user_id: "user-3", user_name: "Omar Ali", rating: 4, comment: "Great quality kit. The app integration works perfectly. Only wish the reservoir was slightly larger.", helpful_count: 8, created_at: "2026-03-05" },
  ],
  "prod-2": [
    { id: "rev-3", product_id: "prod-2", user_id: "user-4", user_name: "Lana Karim", rating: 5, comment: "Best basil I've ever grown. Incredible aroma!", helpful_count: 5, created_at: "2026-03-15" },
  ],
  "prod-5": [
    { id: "rev-4", product_id: "prod-5", user_id: "user-5", user_name: "Dilan Hassan", rating: 5, comment: "Beautiful orchid. Blooming continuously for 3 months now.", helpful_count: 15, created_at: "2026-04-20" },
  ],
};

export const mockNotifications: Notification[] = [
  { id: "notif-1", user_id: "user-1", type: "order", title: "Order Shipped", message: "Your order #002 has been shipped and is on its way!", is_read: false, created_at: "2026-04-28T10:00:00Z" },
  { id: "notif-2", user_id: "user-1", type: "ai_alert", title: "pH Alert", message: "pH levels slightly above optimal range. Consider adding pH Down solution.", is_read: false, created_at: "2026-04-28T08:30:00Z" },
  { id: "notif-3", user_id: "user-1", type: "recommendation", title: "New Arrival", message: "Orchid Blanc is now available! Based on your garden, this would be a perfect addition.", is_read: true, created_at: "2026-04-27T15:00:00Z" },
  { id: "notif-4", user_id: "user-1", type: "low_stock", title: "Low Stock Alert", message: "Nitrogen Booster Pro is running low. Reorder now to avoid gaps.", is_read: true, created_at: "2026-04-26T12:00:00Z" },
  { id: "notif-5", user_id: "user-1", type: "system", title: "System Update", message: "Smart Green v2.0 is here! New AI features and improved sensor accuracy.", is_read: true, created_at: "2026-04-25T09:00:00Z" },
];
